import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

import './globals.css'

import Providers from '@/components/global/Providers'
import {Toaster} from '@/components/ui/Toast'
import {getServerAuthSession} from '@/server/utils/auth'
import ConnectWallet from '@/components/sections/profile/ConnectWallet'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  const session = await getServerAuthSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <nav className="fixed flex h-[90px] w-full items-center justify-end bg-slate-500 p-4">
            <ConnectWallet />
          </nav>
          <div className="flex flex-col pt-[90px]">{children}</div>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}

export default RootLayout
