export * from './primitives'
export {default as DialogContent} from './DialogContent'
export {default as DialogDescription} from './DialogDescription'
export {default as DialogFooter} from './DialogFooter'
export {default as DialogHeader} from './DialogHeader'
export {default as DialogOverlay} from './DialogOverlay'
export {default as DialogTitle} from './DialogTitle'
